apiVersion: v1
kind: Pod
metadata:
  name: kong
spec:
  containers:
    - image: kong:latest
      name: kong
      env:
        - name: KONG_DATABASE
          value: 'off'
        - name: KONG_DECLARATIVE_CONFIG_STRING
          value: '{"_format_version":"1.1", "services":[{"name":"formbackend","url":"http://formbackend:8080","port":8080,"protocol":"http", "routes":[{"paths":["/newBankRequest"]}]}],"plugins":[{"name":"cors", "config":{"origins":["*"]}}]}'
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      ports:
        - containerPort: 8000
          name: http