spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    template-loader-path: classpath:/templates
    suffix: .html
    cache: false
    mode: HTML5
  main:
    allow-circular-references: true
  messages:
    basename: validation
  mail:
    host: smtp.gmail.com
    port: 587
    username: hrmanagerspring@gmail.com
    password: kobnswamlnqcbcdm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true